param(
  [ValidateSet('debug', 'release')]
  [string]$Variant = 'release'
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$sdkRoot = if ($env:ANDROID_SDK_ROOT) { $env:ANDROID_SDK_ROOT } elseif ($env:ANDROID_HOME) { $env:ANDROID_HOME } else { Join-Path $env:LOCALAPPDATA 'Android\Sdk' }
$gradle = Join-Path $projectRoot 'android\gradlew.bat'

if (-not (Test-Path $sdkRoot)) { throw "Android SDK not found: $sdkRoot. Install it with Android Studio first." }
if (-not (Get-Command java -ErrorAction SilentlyContinue)) { throw 'Java not found. Install JDK 17 or newer and reopen the terminal.' }

$env:ANDROID_HOME = $sdkRoot
$env:ANDROID_SDK_ROOT = $sdkRoot
$env:EXPO_NO_DOCTOR = '1'
Push-Location $projectRoot
try {
  # Keep the checked-in native project synchronized with app.json before every build.
  npx expo prebuild --platform android --no-install
  if ($LASTEXITCODE -ne 0) { throw 'Expo prebuild failed.' }
} finally { Pop-Location }
if (-not (Test-Path $gradle)) { throw 'Android project was not generated by Expo prebuild.' }
Push-Location (Join-Path $projectRoot 'android')
try {
  if ($Variant -eq 'debug') { .\gradlew.bat assembleDebug } else { .\gradlew.bat assembleRelease }
} finally { Pop-Location }

$apk = if ($Variant -eq 'debug') { Join-Path $projectRoot 'android\app\build\outputs\apk\debug\app-debug.apk' } else { Join-Path $projectRoot 'android\app\build\outputs\apk\release\app-release.apk' }
if (-not (Test-Path $apk)) { throw "Build finished but APK was not found: $apk" }
Write-Host "`nAPK generated: $apk" -ForegroundColor Green
